# Generated by Django 4.0.5 on 2022-06-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_phone_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
