# Generated by Django 4.0.5 on 2022-06-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='order',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='research',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
