# Generated by Django 4.0.5 on 2022-06-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_research_organization_remove_statement_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('task', models.TextField(verbose_name='описание')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
