# Generated by Django 4.0.5 on 2022-07-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя оператора')),
                ('user_lastname', models.CharField(max_length=50, verbose_name='Фамилие оператора')),
                ('user_patronymic', models.CharField(max_length=50, verbose_name='Отчество оператора')),
                ('user_birthday', models.DateField(verbose_name='Дата рождения')),
                ('user_registration', models.DateField(verbose_name='Дата регистрации пользователя')),
                ('user_phone', models.CharField(max_length=12, verbose_name='Телефон оператора')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_photo', models.ImageField(upload_to='apps/core/templates/core/user_DIR')),
                ('user_rang', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
