# Generated by Django 4.0.5 on 2022-07-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_authentication_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='user_photo',
            field=models.ImageField(upload_to='static'),
        ),
    ]
